// ── Global stubs: keep onclick handlers safe before Firebase auth is ready ──
// The real implementations are defined inside _svAppReady() and will
// overwrite these automatically once the user is authenticated.
(function () {
  var noop = function () {};
  var fns = [
    "toggleWatchlist",
    "openRandom",
    "closeDetail",
    "closeAll",
    "closePlayer",
    "detailOverlayClick",
    "overlayClick",
    "closeSeeAll",
    "toggleNotifPanel",
    "addNotif",
    "toggleTheme",
    "openProfileModal",
    "closeProfileModal",
    "openKbHelp",
    "closeKbHelp",
    "toggleMobileDrawer",
    "closeMobileDrawer",
    "setBottomActive",
    "filterGenre",
    "quickFilter",
    "setActive",
    "openWatchTogetherModal",
    "closeWatchTogetherModal",
    "openCalendarModal",
    "closeCalendarModal",
    "toggleCompare",
    "closeCompare",
    "openCollections",
    "closeCollections",
    "toggleFocusMode",
    "openSleepTimerModal",
    "cancelSleepTimer",
    "toggleTheaterMode",
    "openContent",
    "resumeContent",
    "handleSearch",
    "clearSearch",
    "openFromSearch",
    "shareContent",
    "toggleCompleted",
    "setUserRating",
    "playNow",
    "playEpisodeFromDetail",
    "switchSeason",
    "switchSource",
    "navigateEpisode",
    "removeFromWatchlistByIndex",
    "setViewMode",
    "setSortMode",
    "setMood",
    "addToCompare",
    "removeFromCompare",
    "toggleCompare",
    "toggleReaction",
    "snapCurrentContent",
    "requestPiP",
    "closeRoulette",
    "roulettePlay",
    "wtHostPlay",
    "wtHostPause",
    "wtLeave",
    "wtEndSession",
    "wtCopyLink",
    "wtJoinFromInput",
    "closeWatchTogether",
    "closeTrailerOverlay",
    "deleteComment",
    "submitComment",
    "selectBadge",
    "selectColor",
    "triggerAvatarUpload",
    "saveProfile",
    "wishlistCardClick",
    "switchWlTab",
    "moveWlItem",
    "removeFromMultiWl",
    "toggleWishlistDetail",
    "openIMDb",
    "clearAllCW",
    "removeCW",
    "calPrev",
    "calNext",
    "renderCalendar",
    "toggleParentalLock",
    "closePinOverlay",
    "pinPress",
    "pinClear",
    "setPlaybackSpeed",
    "setSubtitleLang",
    "setWatchGoal",
    "checkAndUnlock",
    "tryUnlock",
  ];
  fns.forEach(function (name) {
    if (typeof window[name] === "undefined") {
      window[name] = noop;
    }
  });
  // checkAndUnlock must return true to allow play
  window.checkAndUnlock = function () {
    return true;
  };
  window.tryUnlock = function () {
    return true;
  };
})();
